In [4]:
import numpy as np
import pandas as pd
import seaborn as sns

In [6]:
iris = sns.dataset.load_iris()

AttributeError: module 'seaborn' has no attribute 'dataset'

In [ ]:
datos= pd.DataFrame(data= np.c_[iris['data'], iris['target']],
                     columns= iris['feature_names'] + ['target'])


In [ ]:
datos

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

# Ejercicio 1: 

Demuestra que la matriz de correlación es una matriz simétrica por los siguientes métodos

*Usando transpuesta

*Usando las matrices triangulares

*Comprobando entrada por entrada

In [ ]:
datos_corr= datos.corr()
datos_corr


sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
target                      0.782561         -0.426658           0.949035   

                   petal width (cm)    target  
sepal length (cm)          0.817941  0.782561  
sepal width (cm)          -0.366126 -0.426658  
petal length (cm)          0.962865  0.949035  
petal width (cm)           1.000000  0.956547  
target                     0.956547  1.000000

In [ ]:
datos_corr.T

sepal length (cm)  sepal width (cm)  petal length (cm)  \
sepal length (cm)           1.000000         -0.117570           0.871754   
sepal width (cm)           -0.117570          1.000000          -0.428440   
petal length (cm)           0.871754         -0.428440           1.000000   
petal width (cm)            0.817941         -0.366126           0.962865   
target                      0.782561         -0.426658           0.949035   

                   petal width (cm)    target  
sepal length (cm)          0.817941  0.782561  
sepal width (cm)          -0.366126 -0.426658  
petal length (cm)          0.962865  0.949035  
petal width (cm)           1.000000  0.956547  
target                     0.956547  1.000000

In [ ]:
np.triu(datos_corr) == np.tril(datos_corr).T


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [ ]:
np.triu(datos_corr)

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [ 0.        ,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.        ,  0.        ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.        ,  0.        ,  0.        ,  1.        ,  0.95654733],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  1.        ]])

In [ ]:
np.tril(datos_corr)

array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.11756978,  1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.        ,  0.        ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.        ],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

In [7]:
datos_corr.columns
datos_corr.axes[0]

NameError: name 'datos_corr' is not defined

In [ ]:
for i in range(len(datos_corr.columns)):
    for j in range(len(datos_corr.columns)):
        if i != j:
            if datos_corr.iloc[i, j] == datos_corr.iloc[j, i]:
                print(datos_corr.columns[i], datos_corr.columns[j])
                print(datos_corr.iloc[i, j], datos_corr.iloc[j, i])
                print('\n')


sepal length (cm) sepal width (cm)
-0.11756978413300088 -0.11756978413300088


sepal length (cm) petal length (cm)
0.8717537758865838 0.8717537758865838


sepal length (cm) petal width (cm)
0.8179411262715758 0.8179411262715758


sepal length (cm) target
0.7825612318100821 0.7825612318100821


sepal width (cm) sepal length (cm)
-0.11756978413300088 -0.11756978413300088


sepal width (cm) petal length (cm)
-0.42844010433053864 -0.42844010433053864


sepal width (cm) petal width (cm)
-0.3661259325364377 -0.3661259325364377


sepal width (cm) target
-0.42665756078112294 -0.42665756078112294


petal length (cm) sepal length (cm)
0.8717537758865838 0.8717537758865838


petal length (cm) sepal width (cm)
-0.42844010433053864 -0.42844010433053864


petal length (cm) petal width (cm)
0.962865431402796 0.962865431402796


petal length (cm) target
0.9490346990083889 0.9490346990083889


petal width (cm) sepal length (cm)
0.8179411262715758 0.8179411262715758


petal width (cm) sepal width (cm)
-

# Ejercicio 2
Obten la matriz inversa de la matriz de correlación

In [ ]:
matriz_inv= np.linalg.inv(datos_corr)
matriz_inv

array([[  7.25653439,  -2.38831293, -11.4928302 ,   2.70178095,
          1.62503903],
       [ -2.38831293,   2.10740433,   4.83544897,  -2.22385256,
          0.30635248],
       [-11.4928302 ,   4.83544897,  34.74887396, -15.51696788,
         -7.07824868],
       [  2.70178095,  -2.22385256, -15.51696788,  20.70668693,
         -8.14391775],
       [  1.62503903,   0.30635248,  -7.07824868,  -8.14391775,
         14.36656146]])

# Ejercicio 3
¿Qué operación(es) harías para obtener la matriz identidad?

In [ ]:
datos_corr.shape

(5, 5)

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])